---
pidfile_path: .robot_sweatshop/run
logfile_path: .robot_sweatshop/log
job_path: .robot_sweatshop/jobs
workspace_path: .robot_sweatshop/workspaces
database_path: .robot_sweatshop/db
http_port: 8080
http_bind: 0.0.0.0
http_cross_origin: true
conveyor_port: 5555
payload_parser_port: 5556
job_dictionary_port: 5557
worker_port: 5558
job_timeout_length: 300 # 5 minutes
